export const words = {
basic: [
      { en: "cat", pt: "gato" },
      { en: "dog", pt: "cachorro" },
      { en: "house", pt: "casa" },
      { en: "sun", pt: "sol" },
      { en: "book", pt: "livro" },
      { en: "car", pt: "carro" },
      { en: "milk", pt: "leite" },
      { en: "water", pt: "água" },
      { en: "bread", pt: "pão" },
      { en: "apple", pt: "maçã" },
      { en: "school", pt: "escola" },
      { en: "pen", pt: "caneta" },
      { en: "chair", pt: "cadeira" },
      { en: "table", pt: "mesa" },
      { en: "window", pt: "janela" },
      { en: "door", pt: "porta" },
      { en: "tree", pt: "árvore" },
      { en: "flower", pt: "flor" },
      { en: "phone", pt: "telefone" },
   ],
   intermediate: [
      { en: "kitchen", pt: "cozinha" },
      { en: "mirror", pt: "espelho" },
      { en: "garden", pt: "jardim" },
      { en: "bottle", pt: "garrafa" },
      { en: "teacher", pt: "professor" },
      { en: "student", pt: ["aluno", "estudante"] },
      { en: "market", pt: "mercado" },
      { en: "clothes", pt: "roupas" },
      { en: "computer", pt: "computador" },
      { en: "keyboard", pt: "teclado" },
      { en: "mouse", pt: "rato" },
      { en: "pencil", pt: "lápis" },
      { en: "notebook", pt: "caderno" },
      { en: "television", pt: "televisão" },
      { en: "refrigerator", pt: "geladeira" },
      { en: "street", pt: "rua" },
      { en: "traffic", pt: "trânsito" },
      { en: "weather", pt: "clima" },
      { en: "holiday", pt: "feriado" },
      { en: "birthday", pt: "aniversário" },
      { en: "medicine", pt: "remédio" },
      { en: "hospital", pt: "hospital" },
      { en: "airplane", pt: "avião" },
      { en: "airport", pt: "aeroporto" },
      { en: "bicycle", pt: "bicicleta" },
      { en: "mountain", pt: "montanha" },
      { en: "river", pt: "rio" },
      { en: "forest", pt: "floresta" },
      { en: "countryside", pt: ["campo", "interior"] },
      { en: "city", pt: "cidade" },
   ],
   advanced: [
      { en: "achievement", pt: ["realização", "conquista"] },
      { en: "development", pt: "desenvolvimento" },
      { en: "relationship", pt: "relacionamento" },
      { en: "government", pt: "governo" },
      { en: "environment", pt: "ambiente" },
      { en: "responsibility", pt: "responsabilidade" },
      { en: "opportunity", pt: "oportunidade" },
      { en: "investment", pt: "investimento" },
      { en: "leadership", pt: "liderança" },
      { en: "partnership", pt: "parceria" },
      { en: "knowledge", pt: "conhecimento" },
      { en: "management", pt: "gestão" },
      { en: "entrepreneur", pt: "empreendedor" },
      { en: "strategy", pt: "estratégia" },
      { en: "sustainability", pt: "sustentabilidade" },
      { en: "technology", pt: "tecnologia" },
      { en: "innovation", pt: "inovação" },
      { en: "negotiation", pt: "negociação" },
      { en: "performance", pt: "desempenho" },
      { en: "efficiency", pt: "eficiência" },
      { en: "productivity", pt: "produtividade" },
      { en: "communication", pt: "comunicação" },
      { en: "motivation", pt: "motivação" },
      { en: "achievement", pt: "conquista" },
      { en: "perception", pt: "percepção" },
      { en: "contribution", pt: "contribuição" },
      { en: "collaboration", pt: "colaboração" },
      { en: "situation", pt: "situação" },
      { en: "evaluation", pt: "avaliação" },
      { en: "qualification", pt: "qualificação" },
      { en: "application", pt: "aplicação" },
      { en: "registration", pt: "registro" },
      { en: "participation", pt: "participação" },
      { en: "interview", pt: "entrevista" },
      { en: "requirement", pt: "requisito" },
      { en: "department", pt: "departamento" },
      { en: "experience", pt: "experiência" },
      { en: "discipline", pt: "disciplina" },
      { en: "laboratory", pt: "laboratório" },
      { en: "experiment", pt: "experimento" },
   ],
}