export const words = {
  basic: [
    { en: "cat", pt: "gato" },
    { en: "dog", pt: "cachorro" },
    { en: "house", pt: "casa" },
    { en: "sun", pt: "sol" },
    { en: "book", pt: "livro" },
    { en: "car", pt: "carro" },
    { en: "milk", pt: "leite" },
    { en: "water", pt: "água" },
    { en: "bread", pt: "pão" },
    { en: "apple", pt: "maçã" },
    { en: "school", pt: "escola" },
    { en: "pen", pt: "caneta" },
    { en: "chair", pt: "cadeira" },
    { en: "table", pt: "mesa" },
    { en: "window", pt: "janela" },
    { en: "door", pt: "porta" },
    { en: "tree", pt: "árvore" },
    { en: "flower", pt: "flor" },
    { en: "phone", pt: "telefone" },
    { en: "bed", pt: "cama" },
    { en: "cup", pt: ["xícara", "copo"] },
    { en: "fork", pt: "garfo" },
    { en: "knife", pt: "faca" },
    { en: "spoon", pt: "colher" },
    { en: "plate", pt: "prato" },
    { en: "shirt", pt: "camisa" },
    { en: "pants", pt: ["calça", "calças"] },
    { en: "shoe", pt: ["sapato", "calçado"] },
    { en: "sock", pt: "meia" },
    { en: "hat", pt: "chapéu" },
    { en: "ball", pt: "bola" },
    { en: "toy", pt: "brinquedo" },
    { en: "game", pt: "jogo" },
    { en: "friend", pt: ["amigo", "amiga"] },
    { en: "family", pt: "família" },
    { en: "man", pt: "homem" },
    { en: "woman", pt: "mulher" },
    { en: "boy", pt: ["menino", "garoto"] },
    { en: "girl", pt: ["menina", "garota"] },
    { en: "baby", pt: "bebê" },
    { en: "time", pt: "tempo" },
    { en: "day", pt: "dia" },
    { en: "night", pt: "noite" },
    { en: "morning", pt: "manhã" },
    { en: "evening", pt: ["noite", "fim de tarde"] }, 
    { en: "yesterday", pt: "ontem" },
    { en: "today", pt: "hoje" },
    { en: "tomorrow", pt: "amanhã" },
    { en: "week", pt: "semana" },
    { en: "month", pt: "mês" },
    { en: "year", pt: "ano" },
    { en: "color", pt: "cor" },
    { en: "red", pt: "vermelho" },
    { en: "blue", pt: "azul" },
    { en: "green", pt: "verde" },
    { en: "yellow", pt: "amarelo" },
    { en: "black", pt: "preto" },
    { en: "white", pt: "branco" },
    { en: "big", pt: "grande" },
    { en: "small", pt: "pequeno" },
    { en: "hot", pt: "quente" },
    { en: "cold", pt: "frio" },
    { en: "happy", pt: "feliz" },
    { en: "sad", pt: "triste" },
    { en: "new", pt: "novo" },
    { en: "old", pt: "velho" },
    { en: "good", pt: "bom" },
    { en: "bad", pt: ["ruim", "mal"] },
    { en: "yes", pt: "sim" },
    { en: "no", pt: "não" },
    { en: "hello", pt: "olá" },
    { en: "bye", pt: ["adeus", "tchau"] },
    { en: "please", pt: "por favor" },
    { en: "thank you", pt: ["obrigado", "obrigada"] },
    { en: "sorry", pt: ["desculpe", "desculpa"] },,
    { en: "fish", pt: "peixe" },
    { en: "eye", pt: "olho" },
    { en: "nose", pt: "nariz" },
    { en: "ear", pt: "orelha" },
    { en: "mouth", pt: "boca" },
    { en: "hand", pt: "mão" },
    { en: "foot", pt: "pé" },
    { en: "bird", pt: "pássaro" },
    { en: "rain", pt: "chuva" },
    { en: "star", pt: "estrela" },
    { en: "sky", pt: "céu" },
    { en: "grass", pt: "grama" },
    { en: "road", pt: "estrada" },
    { en: "carrot", pt: "cenoura" },
    { en: "egg", pt: "ovo" },
    { en: "cake", pt: "bolo" },
  ],
  intermediate: [
    { en: "kitchen", pt: "cozinha" },
    { en: "mirror", pt: "espelho" },
    { en: "garden", pt: "jardim" },
    { en: "bottle", pt: "garrafa" },
    { en: "teacher", pt: ["professor", "professora"] },
    { en: "student", pt: ["aluno", "estudante"] },
    { en: "market", pt: "mercado" },
    { en: "clothes", pt: "roupas" },
    { en: "computer", pt: "computador" },
    { en: "keyboard", pt: "teclado" },
    { en: "mouse", pt: "rato" },
    { en: "pencil", pt: "lápis" },
    { en: "notebook", pt: ["caderno", "bloco de notas"] }, 
    { en: "television", pt: "televisão" },
    { en: "refrigerator", pt: "geladeira" },
    { en: "street", pt: "rua" },
    { en: "traffic", pt: "trânsito" },
    { en: "weather", pt: "clima" },
    { en: "holiday", pt: ["feriado", "férias"] },
    { en: "birthday", pt: "aniversário" },
    { en: "medicine", pt: ["remédio", "medicamento"] }, 
    { en: "hospital", pt: "hospital" },
    { en: "airplane", pt: "avião" },
    { en: "airport", pt: "aeroporto" },
    { en: "bicycle", pt: "bicicleta" },
    { en: "mountain", pt: "montanha" },
    { en: "river", pt: "rio" },
    { en: "forest", pt: "floresta" },
    { en: "countryside", pt: ["campo", "interior"] },
    { en: "city", pt: "cidade" },
    { en: "building", pt: ["prédio", "edifício"] }, 
    { en: "apartment", pt: "apartamento" },
    { en: "office", pt: "escritório" },
    { en: "company", pt: ["empresa", "companhia"] }, 
    { en: "manager", pt: "gerente" },
    { en: "colleague", pt: "colega" },
    { en: "meeting", pt: ["reunião", "encontro"] }, 
    { en: "question", pt: ["pergunta", "questão"] },
    { en: "answer", pt: "resposta" },
    { en: "idea", pt: "ideia" },
    { en: "experience", pt: ["experiência", "vivência"] }, 
    { en: "knowledge", pt: "conhecimento" },
    { en: "skill", pt: ["habilidade", "destreza"] }, 
    { en: "language", pt: ["idioma", "linguagem"] },
    { en: "country", pt: ["país", "nação", "campo"] }, 
    { en: "culture", pt: "cultura" },
    { en: "history", pt: "história" },
    { en: "future", pt: "futuro" },
    { en: "present", pt: ["presente", "atual"] }, 
    { en: "past", pt: "passado" },
    { en: "science", pt: "ciência" },
    { en: "art", pt: "arte" },
    { en: "music", pt: "música" },
    { en: "sport", pt: "esporte" },
    { en: "health", pt: "saúde" },
    { en: "food", pt: "comida" },
    { en: "drink", pt: "bebida" },
    { en: "restaurant", pt: "restaurante" },
    { en: "menu", pt: "cardápio" },
    { en: "bill", pt: ["conta", "nota"] }, 
    { en: "money", pt: "dinheiro" },
    { en: "bank", pt: ["banco", "margem"] }, 
    { en: "store", pt: "loja" }, 
    { en: "price", pt: "preço" },
    { en: "discount", pt: "desconto" },
    { en: "customer", pt: "cliente" },
    { en: "travel", pt: ["viagem", "viajar"] }, 
    { en: "ticket", pt: ["passagem", "ingresso", "bilhete"] }, 
    { en: "beach", pt: "praia" },
    { en: "lake", pt: "lago" },
    { en: "island", pt: "ilha" },
    { en: "earthquake", pt: "terremoto" },
    { en: "flood", pt: "enchente" },
    { en: "fire", pt: "fogo" },
    { en: "smoke", pt: "fumaça" },
    { en: "wind", pt: "vento" },
    { en: "rain", pt: "chuva" },
    { en: "snow", pt: "neve" },
    { en: "cloud", pt: "nuvem" },
    { en: "star", pt: "estrela" },
    { en: "moon", pt: "lua" },
    { en: "machine", pt: "máquina" },
    { en: "engine", pt: "motor" },
    { en: "tool", pt: "ferramenta" },
    { en: "delay", pt: ["atraso", "demora"] }, 
    { en: "fault", pt: ["culpa", "defeito"] }, 
    { en: "trust", pt: ["confiança", "confiar"] }, 
    { en: "guess", pt: ["palpite", "achar", "adivinhar", "adivinhação"] }, 
    { en: "trade", pt: ["comércio", "troca", "negociar"] }, 
    { en: "task", pt: ["tarefa", "ocupação"] }, 
    { en: "deal", pt: ["acordo", "negócio", "lidar"] }, 
    { en: "shift", pt: ["mudança", "turno", "deslocar"] }, 
    { en: "aim", pt: ["objetivo", "mira", "apontar"] }, 
    { en: "pace", pt: ["ritmo", "passo", "andar"] }, 
    { en: "scope", pt: ["alcance", "âmbito", "esquadrinhar", "escopo"] }, 
    { en: "grant", pt: ["concessão", "bolsa", "conceder"] }, 
    { en: "urge", pt: ["impulso", "ânsia", "instar", "urgir"] }, 
    { en: "wage", pt: ["salário", "vencimento", "travar"] },
    { en: "score", pt: ["pontuação", "placar", "marcar"] }, 
    { en: "rule", pt: ["regra", "dominar", "governar"] }, 
    { en: "track", pt: ["trilha", "pista", "rastrear"] }, 
    { en: "link", pt: ["vínculo", "elo", "conectar"] }, 
    { en: "trend", pt: ["tendência", "moda"] },
    { en: "trial", pt: ["tentativa", "julgamento", "prova"] },
    { en: "scheme", pt: ["esquema", "plano", "maquinação"] }, 
    { en: "asset", pt: ["ativo", "bem", "vantagem"] }, 
    { en: "load", pt: ["carga", "peso", "carregar"] },
    { en: "bid", pt: ["oferta", "lance", "licitar"] }, 
    { en: "edge", pt: ["borda", "vantagem", "fio"] }, 
    { en: "claim", pt: ["alegação", "reivindicação", "alegar", "reivindicar"] }, 
    { en: "sue", pt: ["processar", "demandar"] }, 
    { en: "fine", pt: ["multa", "bem", "excelente"] }, 
    { en: "gap", pt: ["lacuna", "intervalo", "brecha"] }, 
    { en: "hint", pt: ["dica", "indício", "sugestão"] }, 
    { en: "bond", pt: ["laço", "vínculo", "título", "ligar"] }, 
    { en: "lease", pt: ["aluguel", "arrendamento", "alugar"] }, 
    { en: "rate", pt: ["taxa", "índice", "avaliar"] }, 
    { en: "gain", pt: ["ganho", "lucro", "ganhar"] }, 
    { en: "loss", pt: ["perda", "prejuízo"] }, 
    { en: "fee", pt: ["taxa", "honorário"] }, 
    { en: "bulk", pt: ["volume", "massa"] },
    { en: "risk", pt: ["risco", "arriscar"] }, 
    { en: "fund", pt: ["fundo", "recurso", "financiar"] }, 
    { en: "share", pt: ["parte", "cota", "compartilhar"] }, 
    { en: "blame", pt: ["culpa", "culpar"] }, 
    { en: "draft", pt: ["rascunho", "projeto", "redigir"] }, 
    { en: "pile", pt: ["pilha", "monte", "empilhar"] }, 
    { en: "tide", pt: ["maré", "tendência"] }, 
    { en: "grasp", pt: ["compreensão", "agarrar", "entender"] }, 
    { en: "trap", pt: ["armadilha", "apanhar"] }, 
    { en: "suit", pt: ["terno", "processo", "servir"] }, 
  ],
  advanced: [
    { en: "feat", pt: ["proeza", "feito"] },
    { en: "growth", pt: ["crescimento", "desenvolvimento"] },
    { en: "bond", pt: ["vínculo", "laço", "ligação"] }, 
    { en: "rule", pt: ["governo", "regra", "domínio"] },
    { en: "surroundings", pt: ["arredores", "ambiente"] }, 
    { en: "duty", pt: ["dever", "obrigação", "tarefa"] },
    { en: "guidance", pt: ["liderança", "orientação", "direção"] },
    { en: "wisdom", pt: ["sabedoria", "discernimento"] }, 
    { en: "oversight", pt: ["gerenciamento", "supervisão", "descuido"] }, 
    { en: "plan", pt: ["plano", "projeto", "planejar"] }, 
    { en: "endurance", pt: ["sustentabilidade", "resistência", "durabilidade"] }, 
    { en: "gadgetry", pt: ["tecnologia", "aparelhagem"] }, 
    { en: "novelty", pt: ["novidade", "inovação", "curiosidade"] },
    { en: "bargain", pt: ["negociação", "barganha", "pechinchar"] },
    { en: "output", pt: ["desempenho", "saída", "produção"] }, 
    { en: "thrift", pt: ["eficiência", "economia", "poupança"] }, 
    { en: "talk", pt: ["comunicação", "conversa", "fala", "falar"] }, 
    { en: "drive", pt: ["motivação", "impulso", "dirigir"] }, 
    { en: "insight", pt: ["percepção", "discernimento", "intuição"] },
    { en: "aid", pt: ["contribuição", "ajuda", "auxílio"] },
    { en: "teamwork", pt: ["colaboração", "trabalho em equipe"] }, 
    { en: "state", pt: ["situação", "estado", "país"] }, 
    { en: "review", pt: ["avaliação", "revisão", "crítica"] }, 
    { en: "aptitude", pt: ["qualificação", "aptidão", "talento"] }, 
    { en: "request", pt: ["aplicação", "solicitação", "pedido"] }, 
    { en: "enrollment", pt: ["registro", "inscrição", "matrícula"] }, 
    { en: "involvement", pt: ["participação", "envolvimento"] },
    { en: "chat", pt: ["entrevista", "conversa"] }, 
    { en: "need", pt: ["requisito", "necessidade", "precisar"] },
    { en: "unit", pt: ["departamento", "unidade", "seção"] }, 
    { en: "rigor", pt: ["disciplina", "severidade", "rigor"] }, 
    { en: "lab", pt: "laboratório"},
    { en: "test", pt: ["experimento", "teste", "prova"] }, 
    { en: "occurrence", pt: ["fenômeno", "ocorrência", "acontecimento"] },
    { en: "breakdown", pt: ["análise", "pane", "colapso"] }, 
    { en: "blend", pt: ["síntese", "mistura", "combinar"] }, 
    { en: "finding", pt: ["conclusão", "descoberta", "achado"] }, 
    { en: "inquiry", pt: ["pesquisa", "investigação", "inquérito"] }, 
    { en: "approach", pt: ["metodologia", "abordagem", "acesso"] }, 
    { en: "notion", pt: ["conceito", "noção", "ideia"] },
    { en: "vague", pt: ["abstrato", "vago", "impreciso"] }, 
    { en: "tangible", pt: ["concreto", "tangível", "palpável"] }, 
    { en: "tenet", pt: ["princípio", "dogma", "crença"] }, 
    { en: "part", pt: ["componente", "parte", "papel"] }, 
    { en: "framework", pt: ["estrutura", "arcabouço"] }, 
    { en: "purpose", pt: ["função", "propósito", "objetivo"] }, 
    { en: "setup", pt: ["sistema", "configuração", "montagem"] }, 
    { en: "web", pt: ["rede", "teia"] }, 
    { en: "gateway", pt: ["interface", "portal", "passagem"] }, 
    { en: "routine", pt: ["algoritmo", "rotina", "hábito"] },
    { en: "code", pt: ["protocolo", "código", "lei"] }, 
    { en: "scramble", pt: ["criptografia", "embaralhar", "disputa"] }, 
    { en: "safety", pt: ["segurança", "salvaguarda"] }, 
    { en: "secrecy", pt: ["privacidade", "sigilo", "segredo"] },
    { en: "proof", pt: ["autenticação", "prova", "comprovação"] }, 
    { en: "permit", pt: ["autorização", "licença", "permitir"] }, 
    { en: "archive", pt: ["arquivo", "arquivar"] }, 
    { en: "host", pt: ["servidor", "anfitrião", "hospedar"] }, 
    { en: "patron", pt: ["cliente", "patrono", "freguês"] }, 
    { en: "scaffold", pt: ["framework", "andaime", "estrutura"] }, 
    { en: "collection", pt: ["coleção", "acervo"] }, 
    { en: "store", pt: ["repositório", "loja", "armazenar"] }, 
    { en: "rollout", pt: ["implantação", "lançamento"] },
    { en: "upkeep", pt: ["manutenção", "conservação"] }, 
    { en: "toughness", pt: ["resiliência", "resistência", "dureza"] }, 
    { en: "design", pt: ["arquitetura", "projeto"] },
    { en: "scheme", pt: ["projeto", "esquema", "ardil"] }, 
    { en: "cycle", pt: ["iteração", "ciclo", "rodar"] }, 
    { en: "input", pt: ["feedback", "entrada", "contribuição"] }, 
    { en: "judgment", pt: ["avaliação", "julgamento", "parecer"] }, 
    { en: "standard", pt: ["métrica", "padrão", "norma"] }, 
    { en: "yardstick", pt: ["parâmetro", "critério", "padrão"] }, 
    { en: "adherence", pt: ["conformidade", "adesão", "observância"] }, 
    { en: "rule", pt: ["regulamentação", "regra", "governar"] }, 
    { en: "stance", pt: ["política", "postura", "posição"] }, 
    { en: "law", pt: ["legislação", "lei", "direito"] }, 
    { en: "domain", pt: ["jurisdição", "domínio", "área"] }, 
    { en: "umpire", pt: ["arbitragem", "árbitro", "juiz"] }, 
    { en: "peacemaking", pt: ["mediação", "pacificação"] }, 
    { en: "quarrel", pt: ["disputa", "briga", "discussão"] }, 
    { en: "settlement", pt: ["resolução", "acordo", "estabelecimento"] }, 
    { en: "haggling", pt: ["negociação", "pechincha"] },
    { en: "agreement", pt: ["consenso", "acordo", "pacto"] },
    { en: "matching", pt: ["alinhamento", "correspondência", "combinação"] }, 
    { en: "ease", pt: ["facilitação", "facilidade", "aliviar"] }, 
    { en: "enablement", pt: ["empoderamento", "capacitação", "habilitação"] }, 
    { en: "handover", pt: ["delegação", "entrega", "passagem"] }, 
    { en: "watch", pt: ["supervisão", "vigilância", "observar", "assistir"] }, 
    { en: "guidance", pt: ["mentoria", "orientação", "direção"] }, 
    { en: "tutoring", pt: ["treinamento", "tutoria"] }, 
    { en: "hiring", pt: ["recrutamento", "contratação"] }, 
    { en: "keeping", pt: ["retenção", "manutenção", "guarda"] }, 
    { en: "pay", pt: ["remuneração", "pagamento", "salário"] }, 
    { en: "perk", pt: ["benefício", "vantagem", "regalia"] }, 
    { en: "lure", pt: ["incentivo", "isca", "atrair"] }, 
    { en: "rise", pt: ["promoção", "aumento", "subida"] }, 
    { en: "downgrade", pt: ["rebaixamento", "desvalorização", "rebaixar"] },
    { en: "quitting", pt: ["demissão", "abandono", "desistência"] }, 
    { en: "grit", pt: "determinação" },
    { en: "whim", pt: "capricho" },
    { en: "quirk", pt: "peculiaridade" },
    { en: "drought", pt: "seca" },
    { en: "slope", pt: "inclinação" },
    { en: "thaw", pt: "degelo" },
    { en: "wreck", pt: "destroço" },
    { en: "hunch", pt: "pressentimento" },
    { en: "glimpse", pt: "vislumbre" },
    { en: "flaw", pt: "falha" },
    { en: "stealth", pt: "furtividade" },
    { en: "wrath", pt: "ira" },
    { en: "grudge", pt: "rancor" },
    { en: "gleam", pt: "brilho" },
    { en: "clutch", pt: "agarrar" },
    { en: "swamp", pt: "pântano" },
    { en: "hassle", pt: "transtorno" },
    { en: "bulk", pt: ["volume", "massa"] }, 
    { en: "doom", pt: ["ruína", "condenação", "fatalidade"] },
    { en: "haste", pt: ["pressa", "apressar-se"] },
    { en: "spree", pt: ["farra", "surtada", "excesso"] },
    { en: "stray", pt: ["perdido", "desviar-se"] }, 
    { en: "stumble", pt: ["tropeçar", "erro"] },
    { en: "scorn", pt: ["desprezo", "desdenhar"] },
    { en: "spunk", pt: ["coragem", "brio"] }, 
    { en: "rubble", pt: ["escombros", "detritos"] },
    { en: "sling", pt: ["atirar", "estilingue", "tipoia"] }, 
    { en: "smug", pt: ["presunçoso", "satisfeito"] }, 
    { en: "slum", pt: ["favela", "cortiço"] }, 
    { en: "dread", pt: ["pavor", "medo", "temor"] }, 
    { en: "nag", pt: ["implicar", "atormentar", "resmungar"] }, 
    { en: "shove", pt: ["empurrão", "empurrar"] },
    { en: "slack", pt: ["folgado", "mole", "lento"] }, 
    { en: "ramp", pt: ["rampa", "acesso"] }, 
    { en: "grunt", pt: ["grunhido", "resmungar"] },
    { en: "moan", pt: ["gemido", "lamento", "gemer"] },
    { en: "crook", pt: ["ladrão", "bandido", "cajado"] },
    { en: "rookie", pt: ["novato", "recruta"] }, 
    { en: "knack", pt: ["jeitinho", "habilidade", "talento"] },
    { en: "flick", pt: ["peteleco", "filme", "movimento rápido"] }, 
    { en: "jolt", pt: ["sacudida", "choque", "sobressalto"] }, 
    { en: "shabby", pt: ["gasto", "puído", "surrado", "malvestido"] },
  ],
};